server:
  port: 8080

# 日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    web: debug
    org.springframework.cloud.openfeign: debug

spring:
  application:
    name: nin-zuul
  profiles:
    active: dev
  zipkin:
    base-url: http://172.16.39.15:9411
    discovery-client-enabled: true
  sleuth:
    sampler:
      probability: 1.0
  # 配置redis
  session:
    store-type: redis
    timeout: 3600
  redis:
    # 指定库
    database: 6
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 50
        min-idle: 5
    timeout: 5000
  datasource:
    url: jdbc:mysql://localhost:3306/nin_workflow?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&nullCatalogMeansCurrent=true&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    #password: Netinnet.2011
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
  kafka:
    bootstrap-servers: 172.16.39.13:9092
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    process-center: /process/**
    education-center: /education/**
  # 忽略匹配，不允许访问通过
  ignored-patterns: /*-center/**
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000   #socket超时

ribbon:
  eager-load:
    enabled: true
  ReadTimeout: 10000
  ConnectTimeout: 10000

# 项目配置
ninzuul:
  shiro:
    # 后端免认证接口 url
    #  /ue/uploadimage, /tGameStudent/importGameStudent, /student/importStudent, /tCourse/importTest, （上传接口）
    anonUrl: /, /index, /education/login, /education/logout, /refreshToken, /error/**, /test/**,
      /fdata/**, /fchart/**, /UEditor/**, /ue/**,/api/**,/sysPermission/getPermissionByRoleCode

app:
  app_id: '@u'
  license: db1c10320edf347c8dae208f1e7539cd
  product: product
  ignore_action:
  cdn_static_url: cdn/static/
  cdn_common_url: cdn/common/
  #本地文件上传保存路径 localFileUtil下配置
  upload_path: /cdn/data/
  temp_path: /cdn/data/temp/
  upload_class_name: cn.netinnet.common.util.file.LocalFileUtil
  cdn_upload_url:
  isOpenLog: true

kafka:
  topic_name_producer: log
  consumer_group_id: log-center
