server:
  port: 9411
  compression:
    enabled: true
spring:
  application:
    name: zipkin-server

management:
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: false